/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Entry.java
 *
 * Created on Apr 12, 2012, 11:46:38 PM
 */
package GUI.Help;

import java.awt.Color;

/**
 *
 * @author Rishabh
 */
public class Entry extends javax.swing.JPanel {

    /** Creates new form Entry */
    public Entry() {
        this("Help text");
    }

    public Entry(String text) {
        this(text,(float)(64/255));
    }

    public Entry(String text, float opacity) {
        initComponents();
        help_text.setText(text);
        setBackground(new Color(0,0,0,(int)(Math.min(1.0, opacity)*255)));
    }

        /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        help_text = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        jLabel2.setText("jLabel2");

        setBackground(new Color(0,0,0,255));

        help_text.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        help_text.setForeground(new java.awt.Color(255, 255, 255));
        help_text.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        help_text.setText("Help text");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(help_text, javax.swing.GroupLayout.DEFAULT_SIZE, 429, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(help_text, javax.swing.GroupLayout.DEFAULT_SIZE, 143, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel help_text;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
