/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * HelpFrame.java
 *
 * Created on Apr 12, 2012, 11:32:15 PM
 */
package GUI.Help;

import java.awt.Color;
import java.awt.GridLayout;
import java.awt.KeyEventDispatcher;
import java.awt.KeyboardFocusManager;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.util.LinkedList;
import java.util.List;

/**
 *
 * @author Rishabh
 */
public class HelpFrame extends javax.swing.JFrame {

    /** Creates new form HelpFrame */
    private List<String> shortcuts;
    public HelpFrame() {
        setUndecorated(true);
        initComponents();
        setTitle("Help");
        setAlwaysOnTop(true);
        setBackground(new Color(0,0,0,0));
        help_panel.setBackground(new Color(0,0,0,50));
        setSize(Toolkit.getDefaultToolkit().getScreenSize());
        shortcuts = new LinkedList<String>();
        shortcuts.add("Press/release up arrow key to send ECU1 pressed/released key event");
        shortcuts.add("Press/release down arrow key to send ECU2 pressed/released key event");
        shortcuts.add("Press/release left arrow key to send ECU3 pressed/released key event");
        shortcuts.add("Press/release right arrow key to send ECU4 pressed/released key event");
        shortcuts.add("Press/release 1 to send extra switch 1 pressed/released key event");
        shortcuts.add("Press/release 2 to send extra switch 2 pressed/released key event");
        shortcuts.add("Press Q/q/Escape to close the emulator");
        shortcuts.add("Press H/h to show help");
        help_panel.setLayout(new GridLayout(shortcuts.size(), 1, 10, 10));
        for(int i=0; i<shortcuts.size();i++){
            help_panel.add(new Entry(shortcuts.get(i), (float)0.8));
        }
        KeyboardFocusManager.getCurrentKeyboardFocusManager().addKeyEventDispatcher(new KeyEventDispatcher() {

         
            @Override
            public boolean dispatchKeyEvent(KeyEvent e) {
                if(!isFocused())
                    return false;
                int code = e.getKeyCode();
                if(e.getID() == KeyEvent.KEY_RELEASED && (code == KeyEvent.VK_Q || code == KeyEvent.VK_ESCAPE || code == KeyEvent.VK_H)){
                    dispose();
                }
                return false;
            }
        });

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        help_panel = new javax.swing.JPanel();
        title_bar = new javax.swing.JPanel();
        close_button = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        javax.swing.GroupLayout help_panelLayout = new javax.swing.GroupLayout(help_panel);
        help_panel.setLayout(help_panelLayout);
        help_panelLayout.setHorizontalGroup(
            help_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        help_panelLayout.setVerticalGroup(
            help_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 289, Short.MAX_VALUE)
        );

        title_bar.setBackground(new Color(0,0,0,200));

        close_button.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        close_button.setForeground(new java.awt.Color(255, 255, 255));
        close_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/closeButton.png"))); // NOI18N
        close_button.setText("Close");
        close_button.setToolTipText("Shourtcut : Q/q/ESC/H/h");
        close_button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeClicked(evt);
            }
        });

        javax.swing.GroupLayout title_barLayout = new javax.swing.GroupLayout(title_bar);
        title_bar.setLayout(title_barLayout);
        title_barLayout.setHorizontalGroup(
            title_barLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, title_barLayout.createSequentialGroup()
                .addContainerGap(318, Short.MAX_VALUE)
                .addComponent(close_button)
                .addContainerGap())
        );
        title_barLayout.setVerticalGroup(
            title_barLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(close_button, javax.swing.GroupLayout.DEFAULT_SIZE, 47, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(title_bar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(help_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(title_bar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(help_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void closeClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeClicked
    dispose();
}//GEN-LAST:event_closeClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HelpFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HelpFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HelpFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HelpFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new HelpFrame().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel close_button;
    private javax.swing.JPanel help_panel;
    private javax.swing.JPanel title_bar;
    // End of variables declaration//GEN-END:variables
}
