/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.komodo.desktop.interfaces;

import com.komodo.desktop.client.BluetoothClient;
import com.komodo.desktop.client.PreferencesHandler;
import java.awt.*;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import javax.swing.JFrame;

/**
 * This is the main window of the TeclaDesktop
 * @author Akhil
 */
public class ClientMain extends javax.swing.JFrame {

    /**
     * Creates new form ClientMain
     */
    public static final String TECLA_ICON_PATH="tekla_icon.png";
    ButtonPref b1,b2,b3,b4,b5,b6;
    BluetoothClient bcl;
    SystemTray systray;
    TrayIcon icon;
    boolean systray_available;
    ConfigSel cfgsel;

    public ClientMain(PreferencesHandler pref,BluetoothClient bcl_) {
        initComponents();
        //Select the desired configurations
        cfgsel=new ConfigSel(this,pref);
        jPanel1.setLayout(new BorderLayout());
        jPanel1.add(cfgsel);
        refresh_display(pref);
        bcl=bcl_;
                
        //Set Application icon in the title bar
        setIconImage(Toolkit.getDefaultToolkit().createImage(TECLA_ICON_PATH));
        //Get the System Tray of the system.
        systray=SystemTray.getSystemTray();
        systray_available=systray.isSupported();
        
        if(systray_available){
            Image icon_img = Toolkit.getDefaultToolkit().createImage(TECLA_ICON_PATH);
            icon=new TrayIcon(icon_img,"TeclaDesktop");
            icon.setImageAutoSize(true);
            icon.addMouseListener(new MouseListener(){

                @Override
                public void mouseClicked(MouseEvent me) {
                    
                    
                    java.awt.EventQueue.invokeLater(new Runnable()
                    {

                        @Override
                        public void run() {
                            setVisible(true);
                            setExtendedState(JFrame.NORMAL);
                            toFront();
                            repaint();
                        }
                    }
                    );
                    systray.remove(icon);
                }

                @Override
                public void mousePressed(MouseEvent me) {
                    
                }

                @Override
                public void mouseReleased(MouseEvent me) {
                    
                }

                @Override
                public void mouseEntered(MouseEvent me) {
                    
                }

                @Override
                public void mouseExited(MouseEvent me) {
                    
                }
            });
        }
    }
    
    public void refresh_display(PreferencesHandler pref)
    {
        //initialize buttonpref panels
        b1=new ButtonPref(ShieldEvent.ECU1,pref);
        b2=new ButtonPref(ShieldEvent.ECU2,pref);
        b3=new ButtonPref(ShieldEvent.ECU3,pref);
        b4=new ButtonPref(ShieldEvent.ECU4,pref);
        b5=new ButtonPref(ShieldEvent.E1,pref);
        b6=new ButtonPref(ShieldEvent.E2,pref);
        //Add button tabs to the panel
        preftab.removeAll();    // Cleanup all tabs
        preftab.addTab("ECU UP",b1);
        preftab.addTab("ECU DOWN",b2);
        preftab.addTab("ECU LEFT",b3);
        preftab.addTab("ECU RIGHT",b4);
        preftab.addTab("SWITCH 1",b5);
        preftab.addTab("SWITCH 2",b6);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        preftab = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        statuslabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("TeclaClient");
        setPreferredSize(new java.awt.Dimension(920, 600));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
            public void windowIconified(java.awt.event.WindowEvent evt) {
                formWindowIconified(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 303, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        statuslabel.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        statuslabel.setText("Welcome to TeclaDesktop !!");
        statuslabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(121, 121, 121)
                        .addComponent(statuslabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(preftab, javax.swing.GroupLayout.PREFERRED_SIZE, 848, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 41, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(statuslabel, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(26, 26, 26)
                .addComponent(preftab, javax.swing.GroupLayout.PREFERRED_SIZE, 411, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
                // TODO add your handling code here:
                bcl.close();
        
    }//GEN-LAST:event_formWindowClosing

    private void formWindowIconified(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowIconified
        // TODO add your handling code here:
        if(systray_available)
            try {
            systray.add(icon);
            setVisible(false);
        } catch (AWTException ex) {
            System.out.println(ex.getMessage());
        }
    }//GEN-LAST:event_formWindowIconified

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ClientMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ClientMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ClientMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ClientMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTabbedPane preftab;
    private javax.swing.JLabel statuslabel;
    // End of variables declaration//GEN-END:variables
    public void AskSelection(String[] option_devices){
        //fires a dialog asking the user which device to connect in case of multiple TeclaShields
        ChooserDialog dl=new ChooserDialog(this,true,option_devices);
        dl.setVisible(true);
    }
    public void onSelectDialog(int index){
        //Connect to a particular device as selected by the user after presing "Select" in the dialog.
        bcl.selectservice(index);
    }
    
    public void setStatus(String message){
        /*
         * Display status message regarding connection status and other information.
         */
        
        statuslabel.setText(message);  //Display message on the main GUI 
        
        if(icon != null){
            //If the GUI is iconified and systemtray is supported, 
            //messages will be dispalyed at the tray icon for some ammount of time.
            icon.displayMessage("TeclaDesktop", message, TrayIcon.MessageType.INFO);
            
        }
    }
}
