/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.akdroid.interfaces;

import com.akdroid.tecladesk.PreferencesHandler;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.File;


/**
 *
 * Configuration selector to provide for and choose between
 * multiple configurations
 * @author ankitdaf
 */
 public class ConfigSel extends javax.swing.JPanel {

    PreferencesHandler pref;
    ClientMain clientmain;
    
    /**
     * Creates new form ConfigSel
     */
    public ConfigSel(ClientMain clientmain_,PreferencesHandler pref_) {
        initComponents();
        pref=pref_;
        show_all_configs();
        clientmain=clientmain_;
        jComboBox1.addActionListener( new ActionListener() {
            
            @Override
            public void actionPerformed(ActionEvent ae) {
                Object obj = jComboBox1.getSelectedItem();
                File selected_config = (File) obj;
                save_current_config();
                set_selected_config(selected_config);
            }
        });
        
    }
    
    public void show_all_configs()
    {
        File[] available_configs = pref.get_available_configs();
        
        for (int i=0;i<available_configs.length;i++)
        {
            jComboBox1.addItem(available_configs[i]);
        }
        jComboBox1.setSelectedItem(pref.get_current_config());
        
    }
    
    public void save_current_config()
    {
        pref.save_config(pref.get_current_config());
    }
    
    public void set_selected_config(File selected_config)
    {
        pref.set_selected_config(selected_config);
        clientmain.refresh_display(pref);
        
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox();

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(103, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox jComboBox1;
    // End of variables declaration//GEN-END:variables

}
